Tech team page
SHPE-UTDallas/Website-Redesign pull request #58
Opened 2021-02-07 01:43 UTC by rigrergl

-double check the paragraph at the beginning and the project descriptions (did I miss anything or do you want anything phrased differently)

-Did you want me to expand the important information to be more graphical rather than in a paragraph? (time commitment, meeting time, benefits of joining)

-Let me know what you think of general page layout

2021-02-07 14:11 UTC, gabriel-flynn requested changes
Bro you knocked it out of the park, the page looks awesome!!! I requested very very minor changes - I love the project cards (the scale transform and drop shadows are a really nice touch) and you nailed it with the descriptions!

2021-02-07 14:11 UTC, gabriel-flynn commented on data/TechTeamProjects.json
> +    "name": "Website-Redeseign",
```suggestion
    "name": "Website-Redesign",
```

2021-02-07 14:11 UTC, gabriel-flynn commented on pages/tech-team.tsx
> +const TeachTeamPage = ({
```suggestion
const TechTeamPage = ({
```

2021-02-07 14:11 UTC, gabriel-flynn commented on pages/tech-team.tsx
> +export default TeachTeamPage;
```suggestion
export default TechTeamPage;
```

2021-02-07 14:11 UTC, gabriel-flynn commented on pages/tech-team.tsx
> +        position={"Technology Chair"}
```suggestion
        position="Technology Chair"
```

2021-02-07 14:11 UTC, gabriel-flynn commented on pages/tech-team.tsx
> +        <a className="button" href="https://www.google.com/" target="_blank">
```suggestion
        <a className="button" href="https://forms.gle/ZGv5Jvk7YYWcgWH76" target="_blank">
```
I guess the interest form is probably the best link for now - I usually don't check it very often unless I had just posted the interest form at a meeting or something like that but I just realized you can get an email notification whenever someone responds so I just enabled that so hopefully that should solve the me not checking the form issue.

2021-02-07 14:11 UTC, gabriel-flynn commented on pages/tech-team.tsx
> +  <Layout title="Tech team page">
```suggestion
  <Layout title="SHPE UTD">
```
Not sure if we should make the title SHPE UTD here as well - I think thats what we've been using on the other pages but honestly we can probably just hardcode the title in the Layout component and remove the title prop entirely if we want every pages title to be SHPE UTD but we could do something like `Tech Team - SHPE UTD` or `SHPE UTD | Tech Team` if we don't want the same title on every page

2021-02-08 05:05 UTC, rigrergl commented
-I forgot to mention it but I changed the <strong> tag to be whatever $primary is set to (will apply throughout the website)
Let me know if I should change it back

2021-02-08 08:42 UTC, gabriel-flynn commented
@rigrergl I think having the same color for <strong> tags could be nice, maybe we should make a section called `Globals` in the _variables.scss file that has those css styles that apply to all elements so that way it's obvious what isn't just a css class or id. 

Speaking of that variables file - I need to try to find other projects using bulma/scss and see how they have their css stuff architected. I feel like theres probably a better way to do it than having like one big scss file (or that could be best practice for all I know - I'm not super in the know with best front-end practices) but I guess it definitely does make it easier to tell what applies to what

2021-02-08 08:45 UTC, gabriel-flynn requested changes
Once you add a `Globals` section or some grouping for styles that apply to a specific HTML elements this looks good to merge!

2021-03-20 03:49 UTC, rigrergl commented
@gabriel-flynn 
Went it and put the <strong> override at the top in a section labeled "GLOBALS"
Branch should be good to merge now

And yeah I don't think having all the styling in this one file is best practice either tbh, should we look into a way to reformat this before the MVP deployment next month, or should we leave that for when we're refining the website?

2021-03-20 18:06 UTC, gabriel-flynn commented
@rigrergl are you sure you pushed the changes? I don't see any new commits.

Yeah I think that's definitely a good idea - at the very least we can break down the styling into a per-page type of thing but I'll try to look into what other react/next.js/bulma/whatever projects are using to find a good solution. I think it'd be fine to deploy it as is for the MVP but I'd definitely like to refactor the scss file sooner rather than later so we don't end up with a lot of tech debt

2021-03-20 19:38 UTC, rigrergl commented
@gabriel-flynn 
Ok yeah my bad I must've lost the changes when I merged with my other branch. The changes should be in now.

By the way we need to change the preview image for the Website-Redesign project on this page cause right now it shows the homepage but it has the broken instagram thing. Whenever we actually fix the instagram component or replace it with the Newsletter component, remind me to change it in case I forget.

2021-04-03 18:52 UTC, gabriel-flynn approved these changes
Looks good, thanks for making those changes!

2021-04-03 18:52 UTC, merged