Shpejr
SHPE-UTDallas/Website-Redesign pull request #69
Opened 2021-04-04 06:27 UTC by techmin

-Centered layout of the whole page, 
-committee member form link
- officer's email for contact(one officer only)
-short description about SHPEjr

2021-04-05 05:47 UTC, gabriel-flynn requested changes
Looks really good! I requested a few minor changes. One thing I didn't include but I think would help a lot is centering the two buttons and the heading above the two buttons with the title - its a little off center right now at least on my screen.

Also adding a picture below the title might help to add more content to the page, this is the image we currently use on the homepage: http://shpeutd.org/images/pic10.jpg

Let me know if you have any questions/don't agree with some of the suggested changes - wasn't sure on what the best wording would be for some things so just put what I thought might be a little clearer, thanks for your time working on this Atmin!

2021-04-05 05:47 UTC, gabriel-flynn commented on pages/shpejr.tsx
> +<Layout title="SHPEjr">
```suggestion
<Layout title="SHPE Jr.">
```

2021-04-05 05:47 UTC, gabriel-flynn commented on pages/shpejr.tsx
> +      SHPEjr
```suggestion
      SHPE Jr.
```

2021-04-05 05:47 UTC, gabriel-flynn commented on pages/shpejr.tsx
> +        Promote STEM in your HIgh School!
```suggestion
       Help promote STEM in local High Schools!
```

2021-04-05 05:47 UTC, gabriel-flynn commented on pages/shpejr.tsx
> +      style ={{textAlign:"center", marginBottom:".5em", marginLeft:"20%",marginRight:"20%",fontSize:"18px"}}
```suggestion
      style ={{textAlign:"justified", marginBottom:".5em", marginLeft:"20%",marginRight:"20%",fontSize:"18px"}}
```

2021-04-05 05:47 UTC, gabriel-flynn commented on pages/shpejr.tsx
> +        ,<button
```suggestion
        <button
```

2021-04-05 05:49 UTC, gabriel-flynn requested changes, later dismissed

2021-04-05 05:49 UTC, gabriel-flynn commented on pages/shpejr.tsx
> +     answering their questions and discussing the benefits and easability of their children going into higher education and STEM.
```suggestion
     &emsp;&emsp;At SHPE UTD, SHPE Jr is our high school outreach program, where we work with local SHPE Jr chapters 
   	 to organize engineering projects, provide academic/professional guidance, and help students foster 
	   a successful future in STEM. The Noche de Ciencias is our premier event, where a whole evening is 
	   dedicated to both the high schoolers and their parents. For the students, we have sessions with 
	   professional engineers and engineering workshops. At the same time, events are held for the parents, 
     answering their questions and discussing the benefits and feasability of their children going into higher education and STEM.
```

2021-04-05 05:49 UTC, gabriel-flynn commented on pages/shpejr.tsx
> +     answering their questions and discussing the benefits and easability of their children going into higher education and STEM.
```suggestion
     &emsp;&emsp;At SHPE UTD, SHPE Jr is our high school outreach program, where we work with local SHPE Jr chapters 
   	 to organize engineering projects, provide academic/professional guidance, and help students foster 
	   a successful future in STEM. The Noche de Ciencias is our premier event, where a whole evening is 
	   dedicated to both the high schoolers and their parents. For the students, we have sessions with 
	   professional engineers and engineering workshops. At the same time, events are held for the parents, 
     answering their questions and discussing the benefits and feasability of their children going into higher education and STEM.
```

2021-05-16 21:42 UTC, techmin commented
made changes manually and giving new request at May 16

2021-05-19 04:59 UTC, rigrergl commented
Awesome progress, I think all the button and text looks really good. Only thing I recommend at the moment is that you center the image. Also make sure to merge with the most current version of dev, let me know if you need help resolving any conflicts.

2021-06-14 17:38 UTC, techmin commented
I have completed the page the image is centered and the button having better responsiveness in larger resolution.

2021-06-15 22:10 UTC, rigrergl approved these changes
Looks awesome, I would just change "Help promote STEM in local High School!" to "Help promote STEM in local High Schools!"

2021-06-15 22:10 UTC, rigrergl commented on pages/shpejr.tsx
> +          Help promote STEM in local High School!
```suggestion
          Help promote STEM in local High Schools!
```

2021-07-12 15:05 UTC, merged